using System;
using System.Collections.Generic;

namespace TheEverythingStore.Models
{

    public class Product
    {
        public int sku { get; init; }
        public object score { get; init; }
        public object productId { get; init; }
        public string name { get; init; }
        public object source { get; init; }
        public string type { get; init; }
        public string startDate { get; init; }
        public bool @new { get; init; }
        public bool active { get; init; }
        public bool lowPriceGuarantee { get; init; }
        public DateTime activeUpdateDate { get; init; }
        public double regularPrice { get; init; }
        public double salePrice { get; init; }
        public bool clearance { get; init; }
        public bool onSale { get; init; }
        public object planPrice { get; init; }
        public List<object> priceWithPlan { get; init; }
        public List<object> contracts { get; init; }
        public object priceRestriction { get; init; }
        public DateTime priceUpdateDate { get; init; }
        public bool digital { get; init; }
        public bool preowned { get; init; }
        public List<object> carriers { get; init; }
        public List<object> planFeatures { get; init; }
        public List<object> devices { get; init; }
        public List<object> carrierPlans { get; init; }
        public object technologyCode { get; init; }
        public object carrierModelNumber { get; init; }
        public List<object> earlyTerminationFees { get; init; }
        public string monthlyRecurringCharge { get; init; }
        public string monthlyRecurringChargeGrandTotal { get; init; }
        public string activationCharge { get; init; }
        public string minutePrice { get; init; }
        public object planCategory { get; init; }
        public object planType { get; init; }
        public object familyIndividualCode { get; init; }
        public object validFrom { get; init; }
        public object validUntil { get; init; }
        public object carrierPlan { get; init; }
        public object outletCenter { get; init; }
        public object secondaryMarket { get; init; }
        public List<object> frequentlyPurchasedWith { get; init; }
        public List<object> accessories { get; init; }
        public List<object> relatedProducts { get; init; }
        public List<object> requiredParts { get; init; }
        public List<object> techSupportPlans { get; init; }
        public List<object> crossSell { get; init; }
        public object salesRankShortTerm { get; init; }
        public object salesRankMediumTerm { get; init; }
        public object salesRankLongTerm { get; init; }
        public object bestSellingRank { get; init; }
        public string url { get; init; }
        public object spin360Url { get; init; }
        public string mobileUrl { get; init; }
        public object affiliateUrl { get; init; }
        public string addToCartUrl { get; init; }
        public object affiliateAddToCartUrl { get; init; }
        public string linkShareAffiliateUrl { get; init; }
        public string linkShareAffiliateAddToCartUrl { get; init; }
        public string upc { get; init; }
        public string productTemplate { get; init; }
        public List<CategoryPath> categoryPath { get; init; }
        public List<object> alternateCategories { get; init; }
        public List<object> lists { get; init; }
        public int customerReviewCount { get; init; }
        public double customerReviewAverage { get; init; }
        public bool customerTopRated { get; init; }
        public string format { get; init; }
        public bool freeShipping { get; init; }
        public bool freeShippingEligible { get; init; }
        public bool inStoreAvailability { get; init; }
        public object inStoreAvailabilityText { get; init; }
        public DateTime inStoreAvailabilityUpdateDate { get; init; }
        public DateTime itemUpdateDate { get; init; }
        public bool onlineAvailability { get; init; }
        public object onlineAvailabilityText { get; init; }
        public DateTime onlineAvailabilityUpdateDate { get; init; }
        public string releaseDate { get; init; }
        public double shippingCost { get; init; }
        public List<Shipping> shipping { get; init; }
        public List<ShippingLevelsOfService> shippingLevelsOfService { get; init; }
        public bool specialOrder { get; init; }
        public object shortDescription { get; init; }
        public string @class { get; init; }
        public int classId { get; init; }
        public string subclass { get; init; }
        public int subclassId { get; init; }
        public string department { get; init; }
        public int departmentId { get; init; }
        public string protectionPlanTerm { get; init; }
        public object protectionPlanType { get; init; }
        public string protectionPlanLowPrice { get; init; }
        public string protectionPlanHighPrice { get; init; }
        public List<object> buybackPlans { get; init; }
        public List<object> protectionPlans { get; init; }
        public List<object> protectionPlanDetails { get; init; }
        public List<object> productFamilies { get; init; }
        public List<object> productVariations { get; init; }
        public object aspectRatio { get; init; }
        public object screenFormat { get; init; }
        public int lengthInMinutes { get; init; }
        public string mpaaRating { get; init; }
        public string plot { get; init; }
        public string studio { get; init; }
        public string theatricalReleaseDate { get; init; }
        public object description { get; init; }
        public object manufacturer { get; init; }
        public string modelNumber { get; init; }
        public List<Image> images { get; init; }
        public string image { get; init; }
        public string largeFrontImage { get; init; }
        public string mediumImage { get; init; }
        public string thumbnailImage { get; init; }
        public string largeImage { get; init; }
        public object alternateViewsImage { get; init; }
        public object angleImage { get; init; }
        public object backViewImage { get; init; }
        public object energyGuideImage { get; init; }
        public object leftViewImage { get; init; }
        public object accessoriesImage { get; init; }
        public object remoteControlImage { get; init; }
        public object rightViewImage { get; init; }
        public object topViewImage { get; init; }
        public string albumTitle { get; init; }
        public object artistName { get; init; }
        public object artistId { get; init; }
        public object originalReleaseDate { get; init; }
        public object parentalAdvisory { get; init; }
        public object mediaCount { get; init; }
        public object monoStereo { get; init; }
        public object studioLive { get; init; }
        public string condition { get; init; }
        public bool inStorePickup { get; init; }
        public bool friendsAndFamilyPickup { get; init; }
        public bool homeDelivery { get; init; }
        public int quantityLimit { get; init; }
        public object fulfilledBy { get; init; }
        public List<object> members { get; init; }
        public List<object> bundledIn { get; init; }
        public object albumLabel { get; init; }
        public string genre { get; init; }
        public object color { get; init; }
        public object depth { get; init; }
        public double dollarSavings { get; init; }
        public string percentSavings { get; init; }
        public string tradeInValue { get; init; }
        public object height { get; init; }
        public string orderable { get; init; }
        public object weight { get; init; }
        public double shippingWeight { get; init; }
        public object width { get; init; }
        public object warrantyLabor { get; init; }
        public object warrantyParts { get; init; }
        public object softwareAge { get; init; }
        public object softwareGrade { get; init; }
        public object platform { get; init; }
        public object numberOfPlayers { get; init; }
        public object softwareNumberOfPlayers { get; init; }
        public object esrbRating { get; init; }
        public string longDescription { get; init; }
        public List<object> includedItemList { get; init; }
        public object marketplace { get; init; }
        public object listingId { get; init; }
        public object sellerId { get; init; }
        public object shippingRestrictions { get; init; }
        public object proposition65WarningMessage { get; init; }
        public string proposition65WarningType { get; init; }
    }


}